# Generated by Django 5.2.5 on 2025-11-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Task description', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', help_text='Task status', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority', max_length=20, verbose_name='Priority')),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline', null=True, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(help_text='Task owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'View and Edit')], default='view', help_text='Access permission level', max_length=10, verbose_name='Permission')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='Shared At')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Share',
                'verbose_name_plural': 'Task Shares',
                'db_table': 'task_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status'], name='tasks_owner_i_a79214_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'priority'], name='tasks_owner_i_775896_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_created_d28591_idx'),
        ),
        migrations.AddIndex(
            model_name='taskshare',
            index=models.Index(fields=['shared_with', 'permission'], name='task_shares_shared__6feae2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskshare',
            index=models.Index(fields=['task'], name='task_shares_task_id_6ed946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskshare',
            unique_together={('task', 'shared_with')},
        ),
    ]
